Added the certificate-acl service to the docker-compose file
dojot/docker-compose pull request #237
Opened 2021-05-19 16:27 UTC by rascaraficci

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
The docker-compose file is missing the certificate-acl service

* **What is the new behavior (if this is a feature change)?**
Added the certificate-acl service to the docker-compose file

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#1939

* **Other information**:

2021-05-19 17:13 UTC, mprevide approved these changes

2021-05-20 12:15 UTC, marianoleonardo approved these changes
LGTM!

2021-05-20 17:00 UTC, mprevide approved these changes
I can't believe I didn't see the image

2021-05-20 18:50 UTC, mprevide requested changes
the img actually is dojot/dojot-acl

2021-05-20 20:02 UTC, mprevide commented on docker-compose.yml
> +      - x509-ejbca
x509-identity-mgmt?

2021-05-21 12:22 UTC, rascaraficci commented on docker-compose.yml
> +      - x509-ejbca
:disappointed:

2021-05-21 12:54 UTC, mprevide commented on docker-compose.yml
> +    image: dojot/certificate-acl:development
the img actually is dojot/dojot-acl

2021-05-21 12:55 UTC, mprevide commented on docker-compose.yml
> +    image: dojot/certificate-acl:development
maybe we can switch to the acl-certificate in github actions (yml)

2021-05-21 12:56 UTC, mprevide commented on docker-compose.yml
> +    image: dojot/certificate-acl:development
I only realized why I put the acl in the version I'm working on, which is for 0.8

2021-05-21 12:58 UTC, mprevide commented on docker-compose.yml
> +    image: dojot/certificate-acl:development
https://github.com/dojot/dojot/pull/2132

2021-05-21 12:58 UTC, mprevide approved these changes

2021-05-21 13:25 UTC, marianoleonardo approved these changes

2021-05-21 19:31 UTC, merged