Adding prometheus and grafana as a service
dojot/docker-compose pull request #253
Opened 2021-08-17 13:07 UTC by gabrielifg

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the current behavior?** (You can also link to an open issue here)

There is currently no support for prometheus and grafana on the DojoT platform with docker compose.

* **What is the new behavior (if this is a feature change)?**

Now we have support for prometheus and grafana on the DojoT platform with docker compose.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

dojot/dojot#2201

* **Other information**:

2021-08-23 20:08 UTC, marianoleonardo requested changes

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/grafana/provisioning/dashboards/dashboards.yml
> +  folder: 'DojoT'
I think you could change `DojoT` to `dojot`

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/grafana/provisioning/datasources/datasource.yml
> +# # config file version
This file is OK, but i think you should remove the comments to make it cleanner.

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/prometheus/prometheus.yml
> +      - targets: ['172.17.0.1:9323'] # 172.17.0.1 porta padrão da interface de rede do docker "docker0"
I think you should translate this part to english.

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/prometheus/prometheus.yml
> +  - job_name: cadvisor
I think you could add a "enter" here to make it easier to distinguish the jobs

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/prometheus/prometheus.yml
> +  - job_name: node_exporter
I think you could add a "enter" here to make it easier to distinguish the jobs

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/prometheus/prometheus.yml
> +  - job_name: docker
I think you could add a "enter" here to make it easier to distinguish the jobs

2021-08-23 20:08 UTC, marianoleonardo commented on monitoring/prometheus/prometheus.yml
> +global:
I think you need to remove some comments as you did in datasource.yaml to make the file cleanner.

2021-08-25 12:48 UTC, gabrielifg commented on monitoring/PROMETHEUS.md
> +* Current status of the container: Running, Stopped and Paused;
Nesse caso Leo, de fato é "and" mesmo, por conta da estrutura no grafana. Lá nos analisamos essas informações em panels separados e não de forma unitária onde você pode ver um "ou" outro.

2021-08-25 12:53 UTC, gabrielifg commented on monitoring/PROMETHEUS.md
> +* Use of memory RAM per container;
Sim sim, a métrica é semelhante mas no dashboard elas são apresentadas de formas diferentes. No primeiro caso, em gráficos e no segundo, em tabelas. No fim, a abordagem é diferente.

2021-09-02 12:23 UTC, marianoleonardo requested changes
I left some comments

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +* RSS Memory Usage per Container
You should write a `;` at the end of the text

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +*  RAM limit established for each container
You should write a `.` at the end of the text

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +If the file is not empty, add these two keys, making sure the resulting file is a valid JSON. Be careful that all lines end with a comma  "," except the last line.
There is two spaces between `comma` and `","`. You should remove one.
i think you should add a `must` between `lines` and `end` like this:
```
Be careful that all lines must end...
```

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +*   [Metrics Docker](http://localhost:9323/metrics).
Change to `Docker Metrics`

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +*   [Metrics Prometheus](http://localhost:9090/metrics).
Change to `Prometheus Metrics`

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +Visually, it is possible to check if everything is "UP" by [Targets Prometheus](http://localhost:9090/targets).
Change to `Prometheus Targets`

2021-09-02 12:23 UTC, marianoleonardo commented on monitoring/grafana/provisioning/dashboards/dashboards.yml
> +
I think you could remove this extra line in the beginning of the file.

2021-09-02 12:30 UTC, marianoleonardo commented on monitoring/PROMETHEUS.md
> +Since we are running prometheus on localhost, in case we try to use the docker as localhost as well. Prometheus would understand that the metrics would be inside the service itself (prometheus) and t
I think you need to make this changes.

2021-09-02 13:43 UTC, marianoleonardo approved these changes
Great job! 👏🏼👏🏼

2021-09-02 17:57 UTC, danielapetito approved these changes

2021-09-02 19:23 UTC, merged