Update grafana
dojot/docker-compose pull request #280
Opened 2021-12-17 21:10 UTC by gabrielifg

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

bug fixes

* **What is the current behavior?** (You can also link to an open issue here)

Currently, the grafana version is out of date and contains vulnerability issues. Also some exporters, CAdvisor and node exporter have ports and "context deadline" issues presented by promethues in targets panel.

* **What is the new behavior (if this is a feature change)?**

The grafana version has been updated, and the CAdvisor and Node Exporter services are working as planned.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

dojot/dojot#2401

* **Other information**:

2021-12-23 11:49 UTC, ewerton-silva00 requested changes
You can remove the CAdvisor's ports publication. We will use these ports only in cases of troubleshooting.

2021-12-27 12:22 UTC, gabrielifg commented on monitoring/docker-compose-monitoring.yaml
> +    ports:
Okay, i will remove

2021-12-27 13:04 UTC, ewerton-silva00 approved these changes
Thank you! 👏🏼

2021-12-27 13:17 UTC, danielapetito commented on docker-compose.yml
> +      - 3110:3000
A atualização do grafana precisa alterar porta do basic- auth ?

Pergunto pq aí precisa ajustar no K8S/Ansible.

2021-12-27 14:11 UTC, gabrielifg commented on docker-compose.yml
> +      - 3110:3000
Sim Dani, analisei os dois serviços, alterar a porta do grafana seria mais custoso.

2021-12-27 14:35 UTC, danielapetito commented on docker-compose.yml
> +      - 3110:3000
mas isso não terá impacto nos outros serviços ?
não seria interessante alinhar com o Gil @gilmaicor ?

2021-12-28 15:05 UTC, danielapetito approved these changes
ok

2021-12-28 15:31 UTC, merged