update docker-compose keycloak
dojot/docker-compose pull request #310
Opened 2022-08-02 18:03 UTC by abeserrab

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-08-02 18:33 UTC, rodrigoaasm requested changes
Foi adicionado alguns itens descontinuados. E não foi adicionado nenhum profile nos itens que já existiam. O objetivo da tarefa era revisar os profiles dos serviços.

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +  history:
O history foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +    image: dojot/persister:${DOJOT_VERSION}
O Persister foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +  gui:
A GUI foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +    image: dojot/gui-v2:${DOJOT_VERSION}
O gui-v2 foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +    image: dojot/data-broker:${DOJOT_VERSION}
O data-broker foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +  data-broker-redis:
O data-broker foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +  iotagent-lwm2m:
O Iotagent-lwm2m foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +    image: dojot/image-manager:${DOJOT_VERSION}
O image-manager foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
> +    image: dojot/auth:${DOJOT_VERSION}
O Auth foi descontinuado da dojot versão keycloak

2022-08-02 18:33 UTC, rodrigoaasm commented on docker-compose.yml
>    container-nx:
Esse serviços estão sem profile.

2022-08-02 18:34 UTC, rodrigoaasm commented on docker-compose.yml
>    container-nx:
Existem vários serviços sem profile

2022-08-02 22:08 UTC, abeserrab commented on docker-compose.yml
> +  history:
Tirei

2022-08-02 22:08 UTC, abeserrab commented on docker-compose.yml
> +    image: dojot/persister:${DOJOT_VERSION}
tirei O Persister foi descontinuado da dojot versão keycloak

2022-08-02 22:08 UTC, abeserrab commented on docker-compose.yml
> +  gui:
tirei A GUI foi descontinuado da dojot versão keycloak

2022-08-02 22:09 UTC, abeserrab commented on docker-compose.yml
> +    image: dojot/gui-v2:${DOJOT_VERSION}
tirei O gui-v2 foi descontinuado da dojot versão keycloak

2022-08-02 22:09 UTC, abeserrab commented on docker-compose.yml
> +    image: dojot/data-broker:${DOJOT_VERSION}
tirei O data-broker foi descontinuado da dojot versão keycloak

2022-08-02 22:09 UTC, abeserrab commented on docker-compose.yml
> +  data-broker-redis:
Tirei O data-broker foi descontinuado da dojot versão keycloak

2022-08-02 22:10 UTC, abeserrab commented on docker-compose.yml
> +  iotagent-lwm2m:
tirei o Iotagent-lwm2m foi descontinuado da dojot versão keycloak

2022-08-02 22:10 UTC, abeserrab commented on docker-compose.yml
> +    image: dojot/auth:${DOJOT_VERSION}
tirei O Auth foi descontinuado da dojot versão keycloak

2022-08-02 22:10 UTC, abeserrab commented on docker-compose.yml
> +    image: dojot/image-manager:${DOJOT_VERSION}
Tirei O image-manager foi descontinuado da dojot versão keycloak

2022-08-02 22:10 UTC, abeserrab commented on docker-compose.yml
>    container-nx:
Ajustei os profile

2022-08-03 17:56 UTC, gabrielifg approved these changes

2022-08-03 19:40 UTC, closed without merging