[DEVOPS-435] Docker-compose - Self Signed Certificate Nginx
dojot/docker-compose pull request #314
Opened 2022-08-18 14:42 UTC by danielapetito

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
[Docker-compose] Self Signed Certificate Nginx

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:
[DEVOPS-435](https://jira.cpqd.com.br/browse/DEVOPS-435) [DOJOT] Ambiente de teste (e outros) deve ter https para acessos ao Kong

2022-08-19 18:30 UTC, marianoleonardo requested changes
Deixei alguns comentários

2022-08-19 18:41 UTC, danielapetito commented on README.md
> +Now you nedd to click on the warning botton next to your IP address.
corrigido

2022-08-19 18:42 UTC, danielapetito commented on README.md
> +To get dojot running with https with self-signed certificate, that domain/ip must be accessible where dojot is running and inside the docker network.
corrigido

2022-08-19 18:43 UTC, danielapetito commented on README.md
> +The next step, it is uploading the certificate (that you exported) in your browser.
corrigido

2022-08-19 18:44 UTC, danielapetito commented on README.md
> +CERT_SC_CERTS_HOSTNAMES: '["http-agent", "${DOJOT_DOMAIN_NAME:-localhost}", "<server IP>", "<server Name>"]'
alterado

2022-08-19 18:45 UTC, danielapetito commented on self-signed-certificate-nginx/docker-compose-dojot-https-self-signed-certificate.yml
> +
corrigido

2022-08-19 20:29 UTC, gabrielifg approved these changes
bom trabalho!!!

2022-08-22 11:07 UTC, marianoleonardo approved these changes

2022-08-22 11:08 UTC, merged