Merge branch 'feature/keycloak-v2' into development
dojot/docker-compose pull request #319
Opened 2022-09-13 13:00 UTC by marianoleonardo

Merge branch 'feature/keycloak-v2' into development

2022-09-13 13:25 UTC, gabrielifg submitted a review, later dismissed
GG!!!

2022-09-14 13:11 UTC, abeserrab submitted a review, later dismissed

2022-09-14 13:19 UTC, rodrigoaasm requested changes
I added some comments that resulted in the necessary changes. Some changes should have been applied in the feature/keycloak-v2 branch. Could you apply these changes for me. Thanks.

2022-09-14 13:19 UTC, rodrigoaasm commented on docker-compose.yml
> +    ports:
Acho que podemos remover essas portas.

2022-09-14 13:19 UTC, rodrigoaasm commented on docker-compose.yml
> +      FILEMGMT_LOG_CONSOLE_LEVEL: "info"
Ocorreu varias modificações nesse docker-compose e nessas modificações essa linha se perdeu:
FILEMGMT_MINIO_BUCKET_SUFFIX: ${MINIO_BUCKET_SUFFIX}

2022-09-14 13:19 UTC, rodrigoaasm commented on .env
> -MINIO_BUCKET_SUFFIX=cpqd.dojot.
Essa variável deve existir, por causa da configuração do file-mgmt (FILEMGMT_MINIO_BUCKET_SUFFIX: ${MINIO_BUCKET_SUFFIX})

2022-09-14 13:19 UTC, rodrigoaasm commented on secrets/.KEYCLOAK_PROXY
> +$5$xx3cIrHn421.LBvg$DXZDVlRzBoPs4RoEnDTsVefQzvtn9JRpsljk2vcekk5
Esse arquivo era para ser ignorado pelo git.

2022-09-14 13:19 UTC, rodrigoaasm commented on secrets/KEYCLOAK_PROXY
> +$5$Rw43eQvptLWA8y4o$P9mnDwgeKMzui.2Yj2w4AfTCWAx7x8A4UrbOJXm/uo7
Esse arquivo era para ser ignorado pelo git.

2022-09-14 13:19 UTC, rodrigoaasm commented on secrets/KEYCLOAK_PROXY_USER
> +$5$eEZyQ5XTWz5UBjEy$05jxKTsy/14MVPClNkNuS6j02PhZowyZgaOPXrD.sOA
Esse arquivo era para ser ignorado pelo git.

2022-09-16 13:16 UTC, abeserrab approved these changes

2022-09-16 17:06 UTC, merged