Feature - Report Manager
dojot/docker-compose pull request #326
Opened 2022-10-27 16:29 UTC by LuanEdCosta

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
No configs for the Report Manager service

* **What is the new behavior (if this is a feature change)?**
Report Manager services and configs added

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
No. But take a look at the epic: https://dojot.atlassian.net/browse/DOJOT-30

2022-10-28 12:20 UTC, danielapetito submitted a review, later dismissed

2022-10-28 12:39 UTC, marianoleonardo approved these changes

2022-11-03 16:17 UTC, rodrigoaasm requested changes

2022-11-08 16:32 UTC, marianoleonardo approved these changes

2022-11-08 16:33 UTC, danielapetito approved these changes

2022-11-22 16:05 UTC, rodrigoaasm approved these changes
Approved!

2022-11-22 16:08 UTC, merged