[DOJOT48] - Feature/dojot 48 - device manager batch - remove device and templates
dojot/docker-compose pull request #337
Opened 2022-11-23 12:52 UTC by MarceloPimentel050975

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)
- 
Add feature/Dojot-48 operation remove devices and templates.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-11-23 13:08 UTC, danielapetito submitted a review, later dismissed

2022-11-23 13:48 UTC, marianoleonardo requested changes
Deixei um comentário.

2022-11-23 13:48 UTC, marianoleonardo commented on kong/kong.config.sh
> +createEndpoint "device-manager-batch" "http://device-manager-batch:8089" '"/device-manager-batch"' "true"
Sugiro que você pule uma linha aqui para separar o serviço `device-manager-batch` do restante dos serviços da `gui-nx`.

Seria legal também colocar um comentário assim na linha de cima do serviço (pra seguir o padrão dos demais serviços):
```
# service: device-manager-batch
```

2022-11-23 13:57 UTC, MarceloPimentel050975 commented on kong/kong.config.sh
> +createEndpoint "device-manager-batch" "http://device-manager-batch:8089" '"/device-manager-batch"' "true"
Ok leo vou realizar alteração.

2022-11-24 12:55 UTC, danielapetito submitted a review, later dismissed

2022-11-25 18:13 UTC, LuanEdCosta commented
@rodrigoaasm @marianoleonardo @danielapetito @MarceloPimentel050975
O serviço de batch também não precisa ter autenticação adicionada ao endpoint do kong?

Observe outros serviços: 
![image](https://user-images.githubusercontent.com/36794274/204037884-fdfc1bb1-0c90-4052-812d-6100d0db031d.png)

Endpoints do kong sem autenticação são aqueles que o usuário pode acessar "por fora" sem precisar logar, estou certo?

2022-11-28 17:19 UTC, danielapetito approved these changes

2022-11-28 19:37 UTC, LuanEdCosta approved these changes

2022-11-28 19:38 UTC, LuanEdCosta commented on docker-compose.yml
>    device-manager-sidecar:
Só acho que poderia ter um espaço entre os serviços. Mas aprovei e corrigimos depois!

2022-11-28 19:41 UTC, marianoleonardo approved these changes
Falta implementar também o healthcheck desse serviço, mas também podemos implementar depois..

2022-11-29 12:18 UTC, merged